### ISSUE TITLE
resourceHints is not optional

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/dotcom-page-kit#725]
According to [the docs](https://github.com/Financial-Times/dotcom-page-kit/tree/master/packages/dotcom-ui-shell#resourcehints-string) in the `shell` package, `resourceHints` is optional.

However, if you do not include `resourceHints` in the `props` passed to `shell` component you get the following error:

```
UnhandledPromiseRejectionWarning: TypeError: props.resourceHints is not iterable
    at Shell (/node_modules/@financial-times/dotcom-ui-shell/dist/node/components/Shell.js:38:18)
```

**Comment by i-like-robots** [comment]
Sorry about this - we need to update the docs, the same issue has caught folks out before: #668 🤔 

The problem is that whilst defaults are defined, they are only applied when creating new instances of components via the element factory function rather than calling the component directly:

```js
// no defaults set
const shell = Shell() 

// defaults will get set
const shell = React.createElement(Shell)
```

We recommend using the factory function as this is the interface that's designed and tested.
