### ISSUE TITLE
Preload link missing cross origin for polyfill

### ISSUE THREAD

**Issue by umbobabo** [Financial-Times/dotcom-page-kit#892]
While doing some Lighthouse test for an Application I spotted the following warning that seems to related to Page Kit.

![Screenshot 2021-04-22 at 10 12 34](https://user-images.githubusercontent.com/752680/115708935-83e9dc80-a368-11eb-8200-ae622286b803.png)

Replicable in a current home page running Lighthouse report

**Comment by apaleslimghost** [comment]
the polyfills for `enhanced` browsers [are preloaded](https://github.com/Financial-Times/dotcom-page-kit/blob/0b357c0fbc8f82ae19ba8812e9d2b855df2c4c10/packages/dotcom-ui-bootstrap/lib/bootstrap.js#L48-L58) even if the browser is a `core` browser. it might be that Lighthouse isn't `enhanced` for some reason, so it's not loading that script. we can't change the preload list based on core/enhanced, because it's generated server-side, and we decide core/enhanced based on a [client-side cuts-the-mustard test](https://github.com/Financial-Times/dotcom-page-kit/blob/0b357c0fbc8f82ae19ba8812e9d2b855df2c4c10/packages/dotcom-ui-bootstrap/lib/bootstrap.js#L48-L58).

the `crossorigin` thing is a red herring, this script is loaded by a `<script>` tag so it doesn't require CORS.

**Comment by umbobabo** [comment]
Thanks, closing this then.
